CREATE TABLE IF NOT EXISTS projects(
    id  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK(name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS  tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK(name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
VALUES('Make a Web App', 1, 'Using Javascrip', '2019-05-12');

INSERT INTO projects( name, priority, description, deliverydate)
VALUES ('Make an App', '1', 'Using DART', '2019-05-13');

INSERT INTO projects( name, priority, description, deliverydate)
VALUES ('Make a Desktop App', '2', 'Using C++', '2019-05-14');

    --insert task data
    INSERT INTO tasks (name, done, projectID)
    VALUES ('dowload Vuejs', false, 1);

        INSERT INTO tasks (name, done, projectID)
    VALUES ('create UI WEB', false, 1);

        INSERT INTO tasks (name, done, projectID)
    VALUES ('dowload Fluterr', false, 2);
        INSERT INTO tasks (name, done, projectID)
    VALUES ('Design UI', false, 1);

        --insert dispositvo data
    INSERT INTO dispositivo (porcebatery)
    VALUES ('70');